import fs from 'node:fs';
import {atarFromAggregate} from '../dist/engine.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./boundary-trials.json',import.meta.url))).results;
const bands=[[0,300],[300,440],[440,501]];
export function fit(sample){return bands.map(([min,max])=>{const r=sample.filter(x=>x.aggregate>=min&&x.aggregate<max);if(!r.length)throw Error('Empty calibration band');return {min,max,n:r.length,lowerOffset:Math.floor(Math.min(0,...r.map(x=>x.range[0]-x.atar))*20)/20,upperOffset:Math.ceil(Math.max(0,...r.map(x=>x.range[1]-x.atar))*20)/20};});}
const coverage=[];
for(let g=1;g<=10;g++){const fitBands=fit(rows.filter(r=>r.group!==g));for(const r of rows.filter(r=>r.group===g)){const b=fitBands.find(b=>r.aggregate>=b.min&&r.aggregate<b.max);const lower=Math.min(r.atar+b.lowerOffset,...fitBands.filter(p=>p.min>r.aggregate).map(p=>atarFromAggregate(p.min)+p.lowerOffset));const upper=Math.max(r.atar+b.upperOffset,...fitBands.filter(p=>p.max<=r.aggregate).map(p=>atarFromAggregate(p.max-1e-7)+p.upperOffset));coverage.push({id:r.id,covered:lower<=r.range[0]+1e-8&&upper>=r.range[1]-1e-8});}}
const config={year:'2025',source:'https://atar-navigator.qtac.edu.au/',observed:'2026-09-11',trials:100,minAggregate:Math.min(...rows.map(r=>r.aggregate)),maxAggregate:Math.max(...rows.map(r=>r.aggregate)),subjects:[...new Set(rows.flatMap(r=>r.subjects))].sort(),bands:fit(rows),validation:{method:'Leave one subject set out (10 folds); entire Navigator range contained',covered:coverage.filter(r=>r.covered).length,total:coverage.length}};
fs.writeFileSync(new URL('../dist/boundary-config.mjs',import.meta.url),'// Generated by scripts/build_boundaries.mjs. Synthetic benchmark only.\nexport default '+JSON.stringify(config,null,2)+';\n');
console.log(JSON.stringify(config,null,2));
